% network and block parameter
%  empty PARAM indicates no caffe net
[ConvFeatNet_Param, ConvFeatNet_HasCaffe] = nldetCanonicalizeBlockParam( ...
    'ConvFeatNet', ConvFeatNet_Param, PARAM );
[RegionProposalNet_Param, RegionProposalNet_HasCaffe] = nldetCanonicalizeBlockParam( ...
    'RegionProposalNet', RegionProposalNet_Param, PARAM );
[RegionFeatNet_Param, RegionFeatNet_HasCaffe] = nldetCanonicalizeBlockParam( ...
    'RegionFeatNet', RegionFeatNet_Param, PARAM );
[TextFeatNet_Param, TextFeatNet_HasCaffe] = nldetCanonicalizeBlockParam( ...
    'TextFeatNet', TextFeatNet_Param, PARAM );
[PairNet_Param, PairNet_HasCaffe] = nldetCanonicalizeBlockParam( ...
    'PairNet', PairNet_Param, PARAM );

% batch size
%  empty when no caffe net
%  remark: have particular dependency for canonicalization
ConvFeatNet_BatchSize = nldetCanonicalizeBlockScalar( ...
    ConvFeatNet_BatchSize, BaseModel_BatchSize, ConvFeatNet_HasCaffe);
RegionProposalNet_BatchSize = nldetCanonicalizeBlockScalar( ...
    RegionProposalNet_BatchSize, ConvFeatNet_BatchSize, RegionProposalNet_HasCaffe);
RegionFeatNet_BatchSize = nldetCanonicalizeBlockScalar( ...
    RegionFeatNet_BatchSize, [], RegionFeatNet_HasCaffe);
TextFeatNet_BatchSize = nldetCanonicalizeBlockScalar( ...
    TextFeatNet_BatchSize, [], TextFeatNet_HasCaffe);
PairNet_BatchSize = nldetCanonicalizeBlockScalar( ...
    PairNet_BatchSize, [], PairNet_HasCaffe);

;